<?php
                $fields = array();
                $fields[] = array("Profile" => "select");
                $fields[] = array("Username" => "text");
                $fields[] = array("Password" => "password"); 
                $fields[] = array("Category" =>"select");
                $fields[] = array("Nombre" => "text");    
                $fields[] = array("Apellido PATERNO" =>"text");
                $fields[] = array("Idioma" =>"select");
                $fields[] = array("Deporte" =>"select");
                $fields[] = array("En Qué Año te Gradúas o Graduaste del Bachillerato? " => "select");
                $fields[] = array("En Qué Mes te Gradúas o Graduaste del Bachillerato? " =>"select");
                $fields[] = array("En Qué Semestre Universitario Deseas Ingresar a la Universidad? " => "select");
                $fields[] = array("País" => "select");
                $fields[] = array("Teléfono" => "text"); 
                $fields[] = array("Teléfono #2" =>"text");
                $fields[] = array("Teléfono Oficina Padres #1" => "text");    
                $fields[] = array("Teléfono Oficina Padres #2" => "text");
                $fields[] = array("Teléfono Celular Padres " => "text");
                $fields[] = array("Last Sales/Service Call" => "datepicker");
                $fields[] = array("Next Sales/Service Call" => "datepicker");
                $fields[] = array("Sales Rep" =>"select");
                $fields[] = array("Customer Service Rep " => "select");
                $fields[] = array("Prospect Referred By" => "select");
                $fields[] = array("Ciudad" => "text"); 
                $fields[] = array("Estado/Provincia" =>"text");
                $fields[] = array("E-mail de Deportista" => "text");    
                $fields[] = array("E-mail de Padres #1" => "text");
                $fields[] = array("E-mail de Padres #2" => "text");
                $fields[] = array("Domicilio Linea #1" => "text");
                $fields[] = array("Domicilio Linea #2" => "text");
                $fields[] = array("Código Postal" =>"text");
                $fields[] = array("Fecha de Nacimiento (19yers old)" => "datepicker");
                $fields[] = array("Nombre de Colegio" => "text");
                $fields[] = array("Tipo de Colegio" => "select");
                $fields[] = array("Costo de Colegio Actua" => "select");
                $fields[] = array("Nivel de Ingles (Basico, Intermedio o Avanzado)" => "text");
                $fields[] = array("Como te enteraste de CPOA?" => "text");
                $fields[] = array("Nombre del Club Deportiv" => "text");
                $fields[] = array("Tipo de Club Deportivo" => "select");
                $fields[] = array("Presupuesto de sus Padres para su Educación Universitaria Incluyendo Todos los Gastos " => "select");
                $fields[] = array("CPOA Email" => "text");
                $fields[] = array("Transfer Student " =>"select");
                $fields[] = array("Last Profile Date " => "datepicker");
                $fields[] = array("Mass Email Date " => "datepicker");
                $fields[] = array("Original Contact Date " => "datepicker"); 
                $fields[] = array("Last Contact Date " =>"datepicker");
                $fields[] = array("Client Observations " => "textarea");    
                $fields[] = array("Universidad " => "text");
                $fields[] = array("Division" => "text");
                $fields[] = array("Porcentaje de Beca" => "text");
                $fields[] = array("Costo de Universidad " => "text");
                $fields[] = array("Costo para Familia" =>"text");
   
                $fields[] = array("Estatura en Pies (Multiplica Metros x 3.280 = Pies) " => "text");
                $fields[] = array("Peso en Libras (Pounds) (Multiplica Kilos x 2.205 = libras) " => "text");
                $fields[] = array("Eres Derecho o Zurdo?" => "select");
                $fields[] = array("Club de Golf - Golfistas" => "text");
                $fields[] = array("Handicap - Golf" => "text");
                $fields[] = array("Rating del Campo - Golf " => "text");
                $fields[] = array("Slope del Campo - Golf " => "text");
                $fields[] = array("Promedio de Golpes - Golf" => "text");
                $fields[] = array("Nombre de Entrenador #1 " => "text");
                $fields[] = array("Telefono de Entrenador #1 " => "text");                
 
                $fields[] = array("Email de Entrenador" => "text");
                $fields[] = array("Nombre de Entrenador #2 " => "text");
                $fields[] = array("Telefono de Entrenador #2" => "text");
                $fields[] = array("Email de Entrenador " => "text");
                $fields[] = array("<b>Coaches Corner</b>: Mejor Resultado #1" => "text");
                $fields[] = array("<b>Coaches Corner</b>: Mejor Resultado #2" => "text");
                $fields[] = array("<b>Coaches Corner</b>: Mejor Resultado #3" => "text");
                $fields[] = array("Video Disponible" => "YesNo");
                $fields[] = array("Date Video Edited " => "datepicker");
                $fields[] = array("Resultado del TOEFL" => "text");
                $fields[] = array("Usuario TOEFL" => "text");
                $fields[] = array("Contrasena TOEFL" => "text");               
                $fields[] = array("Fecha del TOEFL " => "datepicker");
                $fields[] = array("Curso del TOEFL" => "text");
                $fields[] = array("Fecha Curso TOEFL" => "datepicker");
                $fields[] = array("<b>Examen del TOEFL</b>" => "YesNo");
                $fields[] = array("<b>Examen del SAT</b>" => "YesNo");
                $fields[] = array("Fecha del SAT I " => "datepicker");  
                $fields[] = array("Usuario SAT" => "text");
                $fields[] = array("Contrasena SAT" => "text");
                $fields[] = array("PSAT Result " => "text");
                $fields[] = array("Curso del SAT " => "YesNo");
                $fields[] = array("Fecha Curso del SAT" => "datepicker");
                $fields[] = array("Resultado SAT Math " => "text");               
                $fields[] = array("Resultado SAT Critical Reading" => "text");
                $fields[] = array("Resultado Total SAT " => "text");
                $fields[] = array("Profile to Process" => "YesNo");
                $fields[] = array("Actual College Enrollment Date" => "datepicker");
                $fields[] = array("Contract Date " => "datepicker");
                $fields[] = array("Ready to Service? " => "YesNo"); 
                $fields[] = array("Contract Received?" => "YesNo");
                $fields[] = array(" Parental Consent? " => "YesNo");
                $fields[] = array("Payment Sheet? " => "YesNo");
                $fields[] = array("Payment? " => "multi_datepicker");
                $fields[] = array("Amount" => "text");
                $fields[] = array("Charged? " => "YesNo");               
                $fields[] = array("Additional Payment " => "datepicker");
                $fields[] = array("Amount" => "text");
                $fields[] = array("Charged? " => "YesNo"); 
                $fields[] = array("Payment Type " => "select");
                $fields[] = array("Credit Card Number " => "text");
                $fields[] = array("Expiration Month" => "select");
                $fields[] = array("Expiration Year" => "text"); 
                $fields[] = array("Security Code " => "text");
                $fields[] = array("Finance Plan? " => "YesNo");
                $fields[] = array("Payment Terms" => "text");
                $fields[] = array("Service " => "select");
                $fields[] = array("<div align='justify'>Mejores Resultados del 2014(?)/2013(?). De ser posibile, poner el LINK de cada resultado para verificarlo en internet. Tenistas y golfistas: Nombrar torneos jugados, fecha, nombre del torneo y resultado. Beisbol y Futbol: Equipos, Campeonatos, Posición. Deportes de Tiempos: Mejores Tiempos en Eventos. Otros: Mejores Resultados a nivel Estatal, Regional o Nacional.</div> " => "textarea");               
                $fields[] = array("Examples of Profiles [Links]" => "select");
                $fields[] = array("Mejores Resultados del 2012(?) " => "textarea");
                $fields[] = array("Información Importante Adicional o Mejores Resultados del 2011(?) " => "text");
                $fields[] = array("Profile To CPOA " => "YesNo");
                $fields[] = array("Profile On Internet" => "YesNo");
                $fields[] = array("Problem Client " => "YesNo");
                $fields[] = array("Recommend Client? " => "YesNo");
                $fields[] = array("Impossible to Contact? " => "YesNo");
                $fields[] = array("Picture Available " => "YesNo");
                $fields[] = array("<b>Registro NAIA</b>" => "YesNo");
                $fields[] = array("Fecha Registro NCAA" => "datepicker");               
                $fields[] = array("Numero ID NCAA " => "text");
                $fields[] = array("Contrasena ID NCAA" => "text");
                $fields[] = array("Numero NCAA EC" => "text");
                $fields[] = array("Password NCAA EC" => "text");
                $fields[] = array("<b>Visa de Estudiante</b>" => "YesNo");
                $fields[] = array("Welcome Call " => "YesNo");
                $fields[] = array("Outlook Rules " => "YesNo");
                $fields[] = array("Welcome Email " => "YesNo");
                $fields[] = array("Email After Profile Sen" => "YesNo");
                $fields[] = array("CPOA Profile Updated " => "YesNo");
                $fields[] = array("Email Password " => "YesNo");
                $fields[] = array("Mass Email Sent " => "YesNo");               
                $fields[] = array("No Interest " => "YesNo");
                $fields[] = array("<b>Reclutado por Univ.</b>" => "YesNo");
                $fields[] = array("<b>Seguro Medico USA</b>" => "YesNo");
                $fields[] = array("Coverage Start Date " => "datepicker");
                $fields[] = array("Semester Coverage " => "YesNo");
                $fields[] = array("Annual Coverage " => "YesNo");
                $fields[] = array("Posicion Deportiva Blue Chip " => "text");
                $fields[] = array("Prospect For D1" => "checkbox");
                $fields[] = array("Prospect For D2" => "checkbox");
                $fields[] = array("Prospect For NAIA" => "checkbox");
                $fields[] = array("Prospect For JC" => "checkbox");
                $fields[] = array("Interested in Div 3 " => "checkbox");

                $fields[] = array("Clave para Verificar Indice" => "text");
                $fields[] = array("Enlace para Verificar Indice " => "text");
                $fields[] = array("Profile Pic " => "text");

?>